---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nodeapp
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: rkmathi/nodeapp
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  type: NodePort
  selector:
    name: nodeapp
  ports:
    - nodePort: 31000
      port: 8080
      targetPort: 8080
      protocol: TCP
