---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nodeapp2
  template:
    metadata:
      labels:
        name: nodeapp2
    spec:
      containers:
        - name: nodeapp
          image: rkmathi/nodeapp
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp2
spec:
  type: NodePort
  selector:
    name: nodeapp2
  ports:
    - nodePort: 31001
      port: 8080
      targetPort: 8080
      protocol: TCP
